### ISSUE TITLE
Waiting for event with timeout

### ISSUE THREAD

**Issue by omelalex** [Azure/durabletask#213]
Hi,

We have faced a problem trying to use orchestration with events.
In our case we have orchestrations that call external service to start async process and need to wait for event indicating if the process succeeded of failed. External service notifies us by sending a message to a specific Service Bus queue and unfortunately we don't control this behavior. We pickup the message and raise event in corresponding orchestration.
We need to fail waiting orchestration in case event was not received in specified timeframe. Basically we just need to wait with timeout.
We use the following code to wait with timeout (eventHandle is an instance of TaskCompletionSource which is completed when we receive an event): 
`await Task.WhenAny(eventHandle.Task, Task.Delay(timeout))`

The problem:
Orchestration execution stops awaiting for any of the task to complete, but when event arrives before timeout a new execution starts which basically continues the orchestration.
Then we might have the following situations depending on timing:
1. The first execution of orchestration continues and fails with timeout which results in failing entire orchestration;
2. Orchestration succeeds, but the first execution continues after completing the orchestration which results in having just an error logged without any additional side effects.

Questions:
1. Is this a bug or it is expected.
2. What is recommended way of waiting for an event with timeout?
3. What approaches would you recommend to handle such cases? 

Any help is very appreciated. 

Thank you!

**Comment by cgillum** [comment]
You should never use `Task.Delay` in an orchestration. It is not safe for replay and can cause your orchestrator to hang in certain situations.  Instead, you should be using durable timers.

The pattern you're trying to implement is very common. See this wiki post for an example showing how you can use Task.WhenAny with durable timers: https://github.com/Azure/durabletask/wiki/Feature---Durable-Timers. (Note: one thing that appears to be missing from that documentation is that you need to use cancellation tokens to cancel durable timers when your external event action completes before the timeout expires - FYI @simonporter since these docs may need to be updated).
