### ISSUE TITLE
TaskActivityDispatcher>RenewUntil cancellation is not handled 

### ISSUE THREAD

**Issue by aanufriyev** [Azure/durabletask#222]
In 2.0.9 cancellation token was added to 
`await Task.Delay(TimeSpan.FromSeconds(5), cancellationToken);`
https://github.com/Azure/durabletask/blob/master/src/DurableTask.Core/TaskActivityDispatcher.cs#L191

This causes unhanded OperationCancelledException to be thrown and there is no handling for it.

Rolling back to 2.0.8 works.

**Comment by cgillum** [comment]
FYI @gfrancomsft I ran into this as well. It was a regression caused by the refactoring change (Commit e5364ae8). It causes the process to crash after running an activity function. The test cases continue to pass, I assume, because mstest re-spawns the process after the crash which makes the issue harder to detect unless you run with a debugger attached.

**Comment by aanufriyev** [comment]
Thank you very much. 🙏
