### ISSUE TITLE
Update package WindowsAzure.Storage to version 9.4.0

### ISSUE THREAD

**Issue by minikolic** [Azure/durabletask#276]
As you know from version 9.4.0 `WindowsAzure.Storage` package has been split into 4 packages, for Blobs, Files, Queues, and Tables.  Because new packages are published under new names, but with same namespaces (except Tables which moved to new namespace `Microsoft.Azure.Cosmos.Table`) we are not able anymore to reference `Microsoft.Azure.Storage.Blob` or `Microsoft.Azure.Storage.Queue` in the same project with DurableTask package. 

`Microsoft.Azure.DurableTask.AzureStorage` is referencing the old version of `WindowsAzure.Storage` so there reference should be updated to version 9.4.0 or higher.

**Comment by ElanHasson** [comment]
I believe the correct move is to use `Microsoft.Azure.CosmosDB.Table`. it's API compatible and seems to be the recommendation for dotnet core/standard.

**Comment by bladepan** [comment]
If we update to Microsoft.Azure.CosmosDB.Table, does that mean we could use cosmosDB as storage layer?

**Comment by cgillum** [comment]
`Microsoft.Azure.DurableTask.AzureStorage` is using an older version of the Azure Storage SDK to maintain compatibility with the Azure Functions runtime (this package was originally created for Azure Functions scenarios). If we were to make this change, we would need to figure out what the impact would be to apps hosted in Azure Functions.

FYI @ConnorMcMahon since we've been talking about this subject recently. We may want to follow up with the Functions team to see what options we have as far as upgrading, especially if we think there may be deadlock risks in the version we're currently using.

**Comment by cgillum** [comment]
We're tracking the update of the Azure Storage SDK dependencies here: https://github.com/Azure/durabletask/issues/516. We'll likely move to one of the newest available versions.
