### ISSUE TITLE
DurableTask.AzureStorage: Improve handling of partition movement to avoid split-brain

### ISSUE THREAD

**Issue by cgillum** [Azure/durabletask#281]
When partitions move, any in-flight instances may get reassigned to different partitions. This can be problematic if an orchestration is in the middle of executing when the movement happens, because state persistance will fail and the episode will need to be re-run from the last checkpoint (resulting in duplicate executions).

There are a couple ways this could be addressed, each with varying degrees of difficulty and benefit:

- [x] Check whether a buffered message should be executed on the current node before attempting to process it. It won't remove the split-brain problem entirely, but this will go a long ways in reducing duplicate work if a worker has already fetched and buffered batches of messages before the partition movement happened.

- [x] Make partition ownership changes "graceful". Specifically, if an existing VM owns a partition which gets reassigned to a new VM, the new VM should not attempt to process any messages for that partition until the previous VM has had a chance to drain its backlog. This could increase latency of message processing during partition movement, but would reduce duplication of work.

**Comment by mark-r-cullen** [comment]
Will this fix the result deserialization issue that I mentioned in #559 ?

**Comment by cgillum** [comment]
@mark-r-cullen can you share a link to your issue? 559 doesn't exist.

**Comment by mark-r-cullen** [comment]
Ok. I think there has just been some misunderstanding then, sorry :)

We are seeing deserialization issues which appear to be caused by the duplicate task ids and having different results logged against against the same id, as shown in the screenshots I included in 559. I had thought based on your responses that this was related to these other issues, but it wasn't fixed by your 1.8.2-private package.

Since that comment we have had a look and think this may just be how we are awaiting activites in the orchestrator, and we have made a change to try a suborchestrator instead.

At the moment we are doing something along the lines of:

`
orchestrator(){
     var tasks = list.Select(x => CreateTasks);

     await Task.WhenAll(tasks);
}

CreateTasks(x) {
     var result1 = await context.CallActivity("a", x);
     var result2 = await context.CallActivity("b", result1);
}
`

Would you expect this to cause some problems, or should it be ok to do this? We are not getting any exception as you do when trying to await say... Task.Delay.

We are basically going to try and change CreateTasks to a suborchestrator - kind of makes sense to do this anyway.

**Comment by cgillum** [comment]
@mark-r-cullen I think it might be better to open a new GitHub issue so that we can separately investigate the issue you're observing. I understand the multiple results issue you mentioned in 559 and how duplicate activity execution could cause it, but I don't understand why that would cause serialization problems since the return _type_ of the activity function is the same in all cases. We might need to look at more detailed orchestration code to understand further. But again, I think the best way to investigate this is to open a separate GitHub issue.

**Comment by cgillum** [comment]
This work has been completed, and is enabled by default in the latest DurableTask.AzureStorage packages on NuGet.
