### ISSUE TITLE
Stuck orchestrations caused by potential deadlock in Azure Storage SDK: CloudQueue.AddMessageAsync

### ISSUE THREAD

**Issue by cgillum** [Azure/durabletask#458]
### Issue
After doing a detailed investigation of an internal customer incident (Xbox), it seems there may be a new Azure Storage SDK deadlock that we're not accounting for in `CloudQueue.AddMessageAsync`. In the specific case I investigated, the hang occurred as part of checkpointing the orchestration.

### Impact
The impact of this issue is that orchestrations might get stuck in the Running state until the process is recycled or until the partition fails over to another worker.

**Comment by govenkat-ms** [comment]
@cgillum Can this be addressed by moving over to the new Storage SDKs? The ones in this package are extremely outdated.

**Comment by cgillum** [comment]
@govenkat-ms yes, I think these deadlocks were fixed in the most recent versions of the storage SDKs. We have to be careful about making this switch, however, because of the impact to app compatibility. This is especially the case for apps running in Azure Durable Functions.

**Comment by ConnorMcMahon** [comment]
I'm curious if we could mitigate this entire class of issue with smarter timeouts in general. My understanding is that the vast majority of storage requests finish fairly quickly, but some small set hit bad networking paths, causing them to take orders of magnitude longer. The longer the request stays open the larger the window for us to hit this deadlock.

The downside of setting a fixed timeout is that there will always be some requests that need that extra time due to size or just intermittent networking slowness. I'm curious if some sort of back-off retry algorithm could help with this?

**Comment by cgillum** [comment]
@ConnorMcMahon My understanding of the problem is that the deadlocks cannot be mitigated by timeouts. We tried a retry strategy in the scale controller by abandoning permanently stuck storage requests and starting new ones, but that resulted in out-of-memory issues because the deadlocks continued until there were so many threads and payloads stuck in memory that we ran out of memory, resulting in even more severe issues.

**Comment by cgillum** [comment]
Closing this as I think we've added deadlock mitigation to the problematic code paths. The final mitigation (tracked elsewhere) should be to use the latest V12+ storage SDKs, which supposedly don't have these deadlock issues.
