### ISSUE TITLE
How will Activity with different parameters work?

### ISSUE THREAD

**Issue by ackava** [Azure/durabletask#538]
# Problem Statement

Consider a video conversion activity, steps,

1. Activity1: Download blob to local file `filePath`
2. Activity2: run ffmpeg on `filePath`
3. Activity3: upload file `filePath` + ".mp4"

In this case filePath cannot be unique to execution, because what if temp file clean up process kicks in and deletes the file as process was recovered from crash.

So in first execution lets say filePath was `c:\file\1.dat`

Execution is interrupted and before firing Activity1 we change filePath to `c:\file\2.dat` because file `1.dat` may or may not have been download successfully or file may not be present.

What will happen if we fire activity 1 with `c:\file\2.dat` argument?

1. Activity1 will be played for `c:\file\2.dat` or not? I assume it should be played.
2. What will happen to previous Activity1 with `c:\file\1.dat`? Will it cause any issue for Orchestration to finish or not? Will Orchestration hang forever as it could not finish first activity?

**Comment by ackava** [comment]
Can anyone please clarify this?

**Comment by ConnorMcMahon** [comment]
I'm not sure I exactly follow the logic you have, but one thing to note is that your orchestrations have to be idempotent, so you can't change the input of Activity1 in between executions. 

Also keep in mind that unless you are running Durable Task Framework on only one VM, many of the backend providers (such as Azure Storage) have their activities run on any of the workers operating on the same taskhub, meaning you aren't guaranteed to run Activity1, Activity2, and Activity3 on the same VM. 

In your case, I would recommend combining Activity1-Activity3 together.

**Comment by ackava** [comment]
Let's say,

Activity1 is called with parameter 1,
Activity2 is called with parameter 2,

server crashes and it is replaying the task...

Activity1 is called with parameter 11
Activity2 is called with parameter 2

What will happen?

1. Activities will be called, but orchestration will be in deadlock as something is still waiting for Activity1 with 1 parameter?
2. Or activities will be called and earlier activity 1 with parameter 1 will be ignored?

I understand idempotency, but I need to understand if an activity is scheduled with different parameter, will it cause orchestration to hang?

**Comment by davidmrdavid** [comment]
Hi @ackava,

Thanks for reaching out. Indeed, the replay behavior of Durable Functions can throw some people off when first encountering it. I'm not certain I understand the scenario you describe, but I suspect it's because we understand the replay behavior differently

I'll do my best to clarify this, please see below.

First, Durable Functions has an "at-least-once" execution model for activities, meaning that if an activity was scheduled but we haven't seen it complete yet, we'll schedule it again! This is why your activities need to be idempotent :) . This is also why it's unlikely you'll see your orchestration "hang".

Next, orchestration replays are powered by an internal data structure that we call the orchestration's "History". The History tracks many things: when was the orchestration scheduled, what inputs did the orchestration receive, what activities have been scheduled, what inputs activities received, what activities have completed, etc. You can think of it as a kind of cache for the orchestration's internal state, and it is precisely what allows us to recover from failures, i.e to be "Durable".

So if a failure occurs mid-way through an orchestration's execution, the history array allows us to reconstruct the orchestrator's internal state up until the moment of failure. One way to think about it is that, as we iterate through your orchestration's API calls, we first check if we have a corresponding result in the "History" array and, if we do, we just grab the result from there. 

This is why, as @ConnorMcMahon mentioned, it's not possible to change Activity inputs midway through an execution, even if a crash occurs. Put differently, if an orchestration instance schedules an activity with input "A", then that fact is recorded in the History and so, if a crash occurs, that History event is persisted and that input will not change. So next time the orchestration replays, after the crash, it will remember that it scheduled that activity with the input "A" and so it will await that result. Then, because of "at-least-once" execution, if the activity itself was affected by the crash, it will just get re-scheduled and complete, allowing the result to be persisted in the History and thus the orchestrator will continue on.

Hopefully that made sense! Please let me know if not!

I do have a question for you, so you mention that your orchestration would have a value `filePath` that is first set to `c:\file\1.dat` and then to `c:\file\2.dat`. Could you clarify how this value is set? Is it the result of an activity or is it the input passed in to the orchestrator? In any case, both values would be cached in the History array, meaning that it would not be possible to change them for a _running_ orchestration. Please let me know if that doesn't make sense, or if you're unsure how to design around it. I have some suggestions but I don't want to overload you with information until we're in the same page about replays 😄 .

**Comment by ackava** [comment]
Hi David,

I don't see your reply on the GitHub issue, did you delete it? I will try
to clarify what I intend to do. However, my only concern was whether old
`cache` will be ignored and orchestration will finish or old cache will
cause orchestration to hang. As you have mentioned that orchestration will
never hang, I think it does help me.

I do not intend to change parameters to the activity, but I have a task
which is fairly big, requires processing huge files, and then creating an
output file (this causes an issue if the previous task fails due to a
process crash, the same filename may not be available). Since activity
actually executes other unmanaged processes, I don't have control over
exceptions and knowing that it failed or succeeded successfully or not.

Thank you,
- Akash Kava

**Comment by cgillum** [comment]
Activities will never be scheduled with different parameters. If Activity 1 returns a path to file1, it’s not possible to change this to file2 later, it will always be file1. This is because the original output of file1 is recorded in the orchestration history immediately after Activity1 completes. After an interruption or rebalance of your orchestration on another VM, replayed calls to activity1 will return the previously recorded output rather than re-executing Activity1. Since you cannot rely on file1 existing on the local VM for activity2 to find, you will instead need to change Activity1 to download the blob locally, run ffmpeg on the local file, and save the output to a new mp4 blob all in one shot, as Connor suggested.

**Comment by ackava** [comment]
@cgillum 

> After an interruption or rebalance of your orchestration on another VM, replayed calls to activity1 will return the previously recorded output rather than re-executing Activity

My question is will orchestration know that I am calling activity with different parameter and will it throw, or will it ignore previous run and execute the activity again?

**Comment by ConnorMcMahon** [comment]
@ackava,

To repeat cgillum's point, each orchestration instance has to execute in the same way each time due to us saving information across the orchestration history. Because of that, you will never get activities called with different parameters for the same orchestration instance if you are following our coding restrictions.

If you write your code in a way that can cause activities to be called with different parameters, than is non-deterministic, and you will almost certainly run into issues. We do a best effort to detect these non-deterministic behaviors by throwing a NonDeterministicOrchestrationException.

**Comment by ackava** [comment]
@ConnorMcMahon Hi, Thanks for clarification, it would be helpful to know how are you trying to detect non-deterministic behavior?

Is following assumption correct?

```
Activity1 is called with parameter 1,
Activity2 is called with parameter 2,

server crashes and it is replaying the task...

Activity1 is called with parameter 11
     throws NonDeterministicOrchestrationException
``

This is the confirmation I have been looking for.

**Comment by davidmrdavid** [comment]
Hi @ackava,

Sorry for causing confusion, I did delete my original answer because I wrote it thinking that you were asking about **Durable Functions** instead of the Durable Task Framework. I wanted to re-post it with an updated answer, but the thread progressed further before I managed to post it. In any case, let's not worry about it, Chris and Connor have already made the main points I wanted to convey :) .

To answer your latest question, you're correct, that would crash with a NonDeterministicOrchestrationException. 
That being said, it's probably a bit dangerous to rely on that behavior. Ideally, there would be no way your orchestration could change a parameter value on a replay, as that goes against the coding constraints (determinism) that the framework expects of orchestrator code.

As others have pointed out, if changing this file name is unavoidable, it might make sense to **combine** all affected activities into just one, and to make that pipeline occur with just one activity call. That way, you encapsulate non-determinism in activities, and keep orchestrators replay-safe.

**Comment by ackava** [comment]
@davidmrdavid Thanks for clarification, however it seems Durable Tasks are not suitable for very large workflows that span across days to months. So I have put together a new framework which allows non deterministic activities by caching activity results. https://github.com/neurospeech/asp-net-core-extensions/tree/dev/Eternity , I would appreciate your feedback on it.

**Comment by ConnorMcMahon** [comment]
@ackava, I am a bit confused about your claim that Durable Tasks are not suited for large workflows that span days to months. The issues we brought up above were specifically with the non-determinism and the fact that most storage providers do not guarantee the locality of activities running on the same VM. 

The Eternity framework you built looks interesting, and has a lot of the syntactic sugar that we have built on top of Durable Task Framework in Durable Functions, though with some very different design decisions around determinism and locality. I do think your decision to move mostly to blobs and tables is interesting, and I think may bypass some of the corner cases we have had to tackle over the years.

**Comment by ackava** [comment]
@ConnorMcMahon thanks for your reply, I just didn't want to start new thread and wanted some opinion on my framework. If you  can enable discussions or want me to make a new thread, we can carry discussion there.

In DurableTasks,
If a VM is executing 100 orchestrations and all of them have timers, VM doesn't do anything, all new orchestrations which can be executed now are stuck unless some other vm picks them up, I was under assumption that if orchestration needs to wait longer, it would throw away the workflow and execute next ones in the line, but it didn't happen in reality. This is not possible unless there is a way to break the `Task` in c#.

The only big difference in Eternity is suspension, `ActivitySuspendedException` breaks the circuit and it allows other queue message to process.

Even if multiple VMs are running, in very rare case same workflow will be picked up. For the same reason I added locking mechanism for activity so only one vm can run an activity. Activity is idempotent by design so even if other vm accidentally picks up same workflow, it will not execute activity again.
