### ISSUE TITLE
Running different activities per hub worker is a supported scenario?

### ISSUE THREAD

**Issue by janek-lopez** [Azure/durabletask#556]
Let's say I have an orchestration (TestOrchestration) and two activities (TestActivity1 and TestActivity2), TestOrchestration runs these activities like this

```
var task1 = context.ScheduleWithRetry<bool>(typeof(TestActivity1), options, "Test Input1");
var task2 = context.ScheduleWithRetry<bool>(typeof(TestActivity2), options, "Test Input2");
```

If TestActivity2 is heavy to process, i may want to have more workers running specifically this task, so i went and create two workers (Worker1 and Worker2) and configure them like this:

Worker1:

```
hubWorker.AddTaskOrchestrations(typeof(TestOrchestration));
hubWorker.AddTaskActivities(typeof(TestActivity1));
```

Worker2:

```
hubWorker.AddTaskOrchestrations(typeof(TestOrchestration));
hubWorker.AddTaskActivities(typeof(TestActivity2));
```

With this setup it works, I can see the Worker1 console executing the first activity and then the Worker2 console shows the execution of the second activity and the completion of the orchestration, but sometimes the whole orchestration runs instantaneously and sometimes the second activity hangs for some time until it finally run and the orchestration is finally completed.

My question is, is this setting supported or am I forcing the framework?

**Comment by cgillum** [comment]
Unfortunately the framework doesn't support this today. Behind the scenes, there is a single queue (the _work-item_ queue) that schedules all activities, and both workers will compete for messages in that queue. If Worker1 gets the message for TestActivity2, then it will fail with an error because TestActivity2 isn't registered in Worker1. It puts the message back on the queue, and after some number of retries Worker2 will finally pick up the message and execute it successfully. Same thing will happen for TestActivity1.

The framework will need a new feature to support multiple queues for activity in order to support your scenario. It's definitely a feature worth having - just not sure when we'll be able to get to it.

**Comment by janek-lopez** [comment]
Thank you! I'm closing this as resolved.
