### ISSUE TITLE
(very) long running workflows

### ISSUE THREAD

**Issue by coronabytes** [Azure/durabletask#601]
Hi, this would be better in discussions, yet they are disabled.

Does your AzureStorage (or SQL / Netherite in the future) storage support and optimize for very long timers or user events?
Like waiting on a timer for 30 days or even 1 year and your engine **completely** offloads this to storage until its time is up?
or does it linger in the queues and are constantly polled by workers till then?
Can I schedule thousands of tasks into the future and the system still performs well with the ones that need to execute now?

Just evaluating potential workflow implementations, and I was wondering how a storage account would even handle that.

**Comment by cgillum** [comment]
* **Azure Storage**: We use invisible messages. I'm not sure how this is implemented on the Azure Storage side, but I believe there is near-zero overhead for these. However, the max lifetime of a message is 7 days, so for periods extending beyond that we distributed the delay into many messages. This results in overhead both in terms of Azure Storage and your the DurableTask.AzureStorage extension when we have to dequeue a timer message (e.g. every 3 days) and replace it with a new invisible message if we discover that it's not yet ready to be consumed.
* **SQL**: Each timer is a row in the database. The current implementation will continuously scan for messages that are ready to be executed, so having lots of timers could result in more expensive scans over time. If it turns out this becomes expensive, we could look into changing the indexes to make this more efficient.
* **Netherite**: My understanding of timers in Netherite is a little rough, so I'll defer to @sebastianburckhardt on this one. I believe it's some combination of keeping them in memory and periodically flushing them into Event Hubs, but I'm probably missing some important details.

**Comment by sebastianburckhardt** [comment]
Regarding **Netherite**: There is an Azure Table that is continuously updated to store information about whether the task hub is idle, and when the next timer will fire. The autoscaling logic periodically checks that table. It scales to zero if all partitions are idle, and from zero if a timer is about to fire. So, from the perspective of the application (e.g. billing in consumption plan) there is zero activity while waiting for a timer, no matter how long.

**Comment by coronabytes** [comment]
Wow that was fast thank you,
Having the task ping up every 3 days or so my not be *that* bad in the beginning, yet the thousands of messages may turn into millions, so I'll better look into the alternative backends or may even roll out our own.
