### ISSUE TITLE
WebJobs/Durable Task + AKS + Horizontal Pod Autoscaler Configured with Resource Metrics

### ISSUE THREAD

**Issue by brrusino** [Azure/durabletask#669]
Hello,

We use the [WebJobs/DTFx implementation](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.DurableTask) for several of our team's microservices, and we are beginning to investigate optimal scaling within our AKS cluster. 

The question I haven't found an answer to yet: if implementing a Kubernetes [Horizontal Pod Autoscaler](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/) triggering off resource metrics (CPU/memory) for our given DTFx service, are there any additional considerations we need to take relative to the number of control queues/partitions we have configured? Referencing [these performance docs](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-perf-and-scale#orchestrator-scale-out), I'm not 100% clear whether scaling from 2 to 4 pods (workers) would automatically redistribute partitions across workers and whether there would be consequences when going back down from 4 to 2 pods again (effect on lease locks & any active orchestrations).

Thanks in advance!

**Comment by cgillum** [comment]
Changing the number of pods/workers should be no problem. Partitions get redistributed automatically, whether you scaling out to more pods/workers or fewer.

FWIW, it's critically important that this work reliably because our primary use-case is Durable Functions, which runs in the Azure Functions hosted service. In that context, apps are scaled automatically from as few as zero workers to as many as 200 workers based on various metrics and failure to keep everything running reliably would result in many support cases. :)

**Comment by brrusino** [comment]
Thanks @cgillum, great explanation (as always). Really appreciate the quick response!
