### ISSUE TITLE
"How to run on M1 system ,  is not compatible."

### ISSUE THREAD

**Issue by liu-song** [Azure/durabletask#884]
hi, all 
I am learning about workflow design in Dapr and want to study DurableTask, but I found that this project cannot run on the M1 system due to the https://github.com/Azure/durabletask/blob/ce209b57db956b0147cc5c070827ea5d9a108399/src/DurableTask.Core/DurableTask.Core.csproj#L5<TargetFrameworks>netstandard2.0;net462</TargetFrameworks>, which includes net462  . As a Go user and a beginner in C#, I am not very familiar with it. 
thanks a lot

**Comment by cgillum** [comment]
Hi @liu-song. It sounds like you're trying to compile the Durable Task Framework code. If you want to simply try building an app, then there's no need to compile this source code, rather, you can simply reference the precompiled Durable Task nuget packages in your own .NET project. For example:

* https://www.nuget.org/packages/Microsoft.Azure.DurableTask.Core/
* https://www.nuget.org/packages/Microsoft.Azure.DurableTask.AzureStorage/

Those packages should be able to run just fine on an M1 system because the build process will automatically select the `netstandard2.0` target, which will be the best match for the version of .NET on your system (for example, .NET 7).

The reason the Durable Task Framework also includes a `net462` target is because there are some users who haven't been able to migrate to newer cross-platform versions of .NET yet and we want to continue supporting them as well. Unfortunately, projects that target `net462` can only be compiled on a Windows machine.

**Comment by cgillum** [comment]
Also, you mentioned that you're a Go user and that you're learning about Dapr Workflow. This repo is actually completely unrelated to Dapr Workflow. I wonder if it would be better for you to study the Go version of the Durable Task Framework, which was created specifically to support Dapr. You can find it here: https://github.com/microsoft/durabletask-go
